language: node_js

node_js:
  - "node"
  - 8

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

install:
  - curl -L https://tarantool.io/installer.sh | VER=2.2 sudo -E bash
  - sudo apt-get install -y tarantool-dev
  - tarantoolctl rocks make
  - tarantoolctl rocks install http 1.0.5

script:
  - npm run lint
  - npm run flow
  - npm ci
  - npm run build_module
  - npm run test_once
  - nohup tarantool example.lua &
  - CYPRESS_BASE_URL=http://localhost:8080 npm run cy:run

env:
  global:
    - ROCK_NAME=frontend-core

jobs:
  include:
    # - tests
    - stage: deploy
      script: skip
      deploy:
        - provider: script
          script: curl --fail -X PUT -F rockspec=@$ROCK_NAME-scm-1.rockspec
            https://$ROCKS_USERNAME:$ROCKS_PASSWORD@$ROCKS_SERVER
        - provider: script
          on: {tags: true}
          script:
            - cat $ROCK_NAME-scm-1.rockspec | sed -E
                -e "s/branch = '.+'/tag = '$TRAVIS_TAG'/g"
                -e "s/version = '.+'/version = '$TRAVIS_TAG-1'/g" >
              $ROCK_NAME-$TRAVIS_TAG-1.rockspec
            - tarantoolctl rocks make $ROCK_NAME-$TRAVIS_TAG-1.rockspec
            - tarantoolctl rocks pack $ROCK_NAME $TRAVIS_TAG-1
            - curl --fail -X PUT -F rockspec=$ROCK_NAME-$TRAVIS_TAG-1.rockspec"
                https://$ROCKS_USERNAME:$ROCKS_PASSWORD@$ROCKS_SERVER
            - curl --fail -X PUT -F "rockspec=@$ROCK_NAME-$TRAVIS_TAG-1.all.rock"
                https://$ROCKS_USERNAME:$ROCKS_PASSWORD@$ROCKS_SERVER

