// @flow
export const UPDATE_LINK: 'UPDATE_LINK' = 'UPDATE_LINK';
export const EXPAND: 'EXPAND' = 'EXPAND';
export const RESET: 'RESET' = 'RESET';

export const TITLE_SET: 'TITLE_SET' = 'TITLE_SET';
export const TITLE_RESET: 'TITLE_RESET' = 'TITLE_RESET';

export const APP_NAME_SET: 'APP_NAME_SET' = 'APP_NAME_SET';

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const PAGE_FILTER_ADD: 'PAGE_FILTER_ADD' = 'PAGE_FILTER_ADD';
export const PAGE_FILTER_REMOVE: 'PAGE_FILTER_REMOVE' = 'PAGE_FILTER_REMOVE';

export const SEND_NOTIFICATION: 'SEND_NOTIFICATION' = 'SEND_NOTIFICATION';
export const HIDE_NOTIFICATION: 'HIDE_NOTIFICATION' = 'HIDE_NOTIFICATION';
export const CHECK_NOTIFICATIONS: 'CHECK_NOTIFICATIONS' = 'CHECK_NOTIFICATIONS';
export const PAUSE_NOTIFICATION_TIMER: 'PAUSE_NOTIFICATION_TIMER' = 'PAUSE_NOTIFICATION_TIMER';
export const UNPAUSE_NOTIFICATION_TIMER: 'UNPAUSE_NOTIFICATION_TIMER' = 'UNPAUSE_NOTIFICATION_TIMER';
export const GARBAGE_NOTIFICATIONS: 'GARBAGE_NOTIFICATIONS' = 'GARBAGE_NOTIFICATIONS';

export const SHOW_NOTIFICATION_LIST: 'SHOW_NOTIFICATION_LIST' = 'SHOW_NOTIFICATION_LIST';
export const HIDE_NOTIFICATION_LIST: 'HIDE_NOTIFICATION_LIST' = 'HIDE_NOTIFICATION_LIST';

export const CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS' = 'CLEAR_NOTIFICATIONS';
